# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/weather_searches', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # WeatherSearch. As you add validations to WeatherSearch, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      WeatherSearch.create! valid_attributes
      get weather_searches_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      weather_search = WeatherSearch.create! valid_attributes
      get weather_search_url(weather_search)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_weather_search_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      weather_search = WeatherSearch.create! valid_attributes
      get edit_weather_search_url(weather_search)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new WeatherSearch' do
        expect do
          post weather_searches_url, params: { weather_search: valid_attributes }
        end.to change(WeatherSearch, :count).by(1)
      end

      it 'redirects to the created weather_search' do
        post weather_searches_url, params: { weather_search: valid_attributes }
        expect(response).to redirect_to(weather_search_url(WeatherSearch.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new WeatherSearch' do
        expect do
          post weather_searches_url, params: { weather_search: invalid_attributes }
        end.to change(WeatherSearch, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post weather_searches_url, params: { weather_search: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested weather_search' do
        weather_search = WeatherSearch.create! valid_attributes
        patch weather_search_url(weather_search), params: { weather_search: new_attributes }
        weather_search.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the weather_search' do
        weather_search = WeatherSearch.create! valid_attributes
        patch weather_search_url(weather_search), params: { weather_search: new_attributes }
        weather_search.reload
        expect(response).to redirect_to(weather_search_url(weather_search))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        weather_search = WeatherSearch.create! valid_attributes
        patch weather_search_url(weather_search), params: { weather_search: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested weather_search' do
      weather_search = WeatherSearch.create! valid_attributes
      expect do
        delete weather_search_url(weather_search)
      end.to change(WeatherSearch, :count).by(-1)
    end

    it 'redirects to the weather_searches list' do
      weather_search = WeatherSearch.create! valid_attributes
      delete weather_search_url(weather_search)
      expect(response).to redirect_to(weather_searches_url)
    end
  end
end
